### ISSUE TITLE
More details?

### ISSUE THREAD

**Issue by trogloditee** [Kongsea/DeepSpectroscopy#1]
Can you explain a few details?
-- what kind of spectroscopy are you using? MR?
-- what kind of output is expected? Quantification of certain resonances at determined frequencies?

**Comment by Kongsea** [comment]
Since my research is focusing on LIBS, Laser Induced Breakdown Spectroscopy, so I will mainly use it.
I am planning to start my research from qualification, and then extend to quantification.
