### ISSUE TITLE
你好，请问深度学习用在LIBS里有效果吗

### ISSUE THREAD

**Issue by gjchunqiu** [Kongsea/DeepSpectroscopy#2]
你好，请问深度学习用在LIBS里有效果吗

**Comment by Kongsea** [comment]
在我仅有的数据集上，传统方法效果已经很好，深度学习的方法并无明显提升。
当然，也可能需要进行针对性地研究，不过我也没有太多时间和精力。
所以，建立这个Repository，希望能抛砖引玉，吸引大家注意这个研究方向。
